import { useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Panel } from '../components/Panel';
import { fade, MONO, SPEC_COLORS, T, ax, tip } from '../theme';

export function ClassroomView({ onBack, classrooms }) {
  const [selected, setSelected] = useState(classrooms[0].id);
  const cls = classrooms.find((c) => c.id === selected) || classrooms[0];
  const maxStudent = useMemo(() => Math.max(1, ...cls.students.map((s) => s.n)), [cls]);
  const maxWeekly = useMemo(() => Math.max(1, ...cls.weekly.map((w) => w.n)), [cls]);
  const dowData = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'].map((d) => ({ day: d, n: cls.byDow[d] || 0 }));
  const maxDow = useMemo(() => Math.max(1, ...dowData.map((d) => d.n)), [cls]);
  const specData = Object.entries(cls.specials).filter(([, v]) => v > 0).map(([k, v]) => ({ name: k, n: v }));

  return <div className="min-h-screen" style={{ background: T.bg, color: T.text }}><div className="mx-auto max-w-6xl px-4 py-5 md:px-6"><div className="flex items-center gap-3 mb-5"><button onClick={onBack} className="text-[11px] px-2.5 py-1.5 rounded" style={{ background: T.surface, border: `1px solid ${T.border}`, color: T.textDim }}>← Admin view</button><div><div className="text-[11px]" style={{ color: T.textDim }}>Wayne STEM Academy · Classroom view · Jan 21 – Apr 1, 2026</div><h1 className="text-xl font-semibold" style={{ color: T.textBright, ...MONO }}>Specials behavior by classroom</h1></div></div>
    <div className="mb-4 space-y-2">{['K', '1', '2', '3', '4', '5', 'EC'].map((grade) => { const gradeClasses = classrooms.filter((c) => c.grade === grade); if (!gradeClasses.length) return null; return <div key={grade} className="flex items-center gap-2 flex-wrap"><span className="text-[10px] font-semibold uppercase tracking-wide w-6 text-right flex-shrink-0" style={{ color: T.textDim }}>{grade === 'EC' ? 'EC' : grade + 'th'}</span>{gradeClasses.map((c) => <button key={c.id} onClick={() => setSelected(c.id)} className="text-[11px] px-2.5 py-1 rounded transition-colors" style={{ background: selected === c.id ? T.accent + '22' : T.surface, border: `1px solid ${selected === c.id ? T.accent + '66' : T.border}`, color: selected === c.id ? T.accent : c.noData ? T.muted : T.textDim, fontWeight: selected === c.id ? 600 : 400 }}>{c.label}{c.noData ? ' –' : ''}</button>)}</div>; })}<p className="text-[10px] pl-8" style={{ color: T.muted }}>Classes marked "–" have no incidents logged in this dataset.</p></div>
    <AnimatePresence mode="wait"><motion.div key={cls.id} {...fade} className="space-y-3">{cls.noData ? <div className="rounded-lg p-6 text-center" style={{ background: T.surface, border: `1px solid ${T.border}` }}><div className="text-[13px] font-semibold mb-1" style={{ color: T.textBright }}>No incidents logged for {cls.label}</div><p className="text-[11px]" style={{ color: T.textDim }}>This class has no records in the Jan 21 – Apr 1, 2026 dataset. This may mean no incidents occurred, or that the form was not used for this class during this period.</p></div> : <>
      <div className="grid grid-cols-2 gap-2 md:grid-cols-4">{[{ label: 'Total incidents', value: cls.total, sub: 'in this class' }, { label: 'Color chart used', value: cls.chart + '%', sub: 'of incidents', flag: cls.chart < 30 }, { label: 'Home contacted', value: cls.home + '%', sub: 'of incidents', flag: cls.home === 0 }, { label: 'Specials logged', value: Object.values(cls.specials).filter((v) => v > 0).length, sub: 'of 4 specials' }].map((k) => <div key={k.label} className="rounded p-3" style={{ background: T.surface, border: `1px solid ${k.flag ? T.alert + '55' : T.border}` }}><div className="text-[10px] uppercase tracking-wide mb-1.5" style={{ color: T.textDim }}>{k.label}</div><span className="text-[22px] font-bold block" style={{ color: k.flag ? T.alert : T.textBright, ...MONO }}>{k.value}</span><div className="text-[10px] mt-0.5" style={{ color: T.textDim }}>{k.sub}</div></div>)}</div>
      <div className="grid gap-3 xl:grid-cols-[1.1fr_1fr]"><Panel title="Behavior types" sub={`${cls.label} · all logged incidents`}><div className="h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={cls.behaviors} layout="vertical" margin={{ left: 12, right: 8 }}><CartesianGrid stroke={T.grid} horizontal={false} /><XAxis type="number" {...ax} /><YAxis type="category" dataKey="type" {...ax} width={122} /><Tooltip {...tip} /><Bar dataKey="n" radius={[0, 3, 3, 0]}>{cls.behaviors.map((d, i) => <Cell key={d.type} fill={d.type === 'Unspecified' ? T.muted : T.series[i % T.series.length]} />)}</Bar></BarChart></ResponsiveContainer></div></Panel><Panel title="Scholars with logged incidents" sub="Specials records only for this class"><div className="space-y-2.5 mt-1">{cls.students.map((s, i) => <div key={s.name}><div className="flex items-center justify-between mb-1"><span className="text-[11px]" style={{ color: s.name === 'Other' ? T.textDim : T.text }}>{s.name}</span><span className="text-[11px] font-semibold" style={{ color: s.n >= 5 ? T.alert : s.n >= 3 ? T.amber : T.textDim, ...MONO }}>{s.n}</span></div><div className="h-1 rounded-full overflow-hidden" style={{ background: T.border }}><motion.div className="h-full rounded-full" style={{ background: s.name === 'Other' ? T.muted : s.n >= 5 ? T.alert : s.n >= 3 ? T.amber : T.accent }} initial={{ width: 0 }} animate={{ width: `${(s.n / maxStudent) * 100}%` }} transition={{ delay: i * 0.04, duration: 0.35 }} /></div></div>)}</div><p className="mt-3 text-[10px] leading-5" style={{ color: T.textDim }}>Specials-only data. Does not include homeroom or office referral records. "Other" = remaining students with 1 incident each.</p></Panel></div>
      <div className="grid gap-3 xl:grid-cols-2"><Panel title="Incidents by day of week" sub="Raw count · not normalized"><div className="h-44"><ResponsiveContainer width="100%" height="100%"><BarChart data={dowData} margin={{ top: 4, right: 4, bottom: 0, left: -14 }}><CartesianGrid stroke={T.grid} vertical={false} /><XAxis dataKey="day" {...ax} /><YAxis {...ax} /><Tooltip {...tip} /><Bar dataKey="n" radius={[3, 3, 0, 0]}>{dowData.map((d) => <Cell key={d.day} fill={d.n === maxDow && maxDow > 0 ? T.alert : T.accent} />)}</Bar></BarChart></ResponsiveContainer></div></Panel><Panel title="Incidents by specials class" sub="Which teachers logged incidents for this classroom"><div className="h-44"><ResponsiveContainer width="100%" height="100%"><BarChart data={specData} margin={{ top: 4, right: 4, bottom: 0, left: -14 }}><CartesianGrid stroke={T.grid} vertical={false} /><XAxis dataKey="name" {...ax} /><YAxis {...ax} /><Tooltip {...tip} /><Bar dataKey="n" radius={[3, 3, 0, 0]}>{specData.map((d) => <Cell key={d.name} fill={SPEC_COLORS[d.name] || T.muted} />)}</Bar></BarChart></ResponsiveContainer></div></Panel></div>
      <Panel title="Incidents by week" sub="Raw count — weeks with no incidents not shown"><div className="h-44"><ResponsiveContainer width="100%" height="100%"><BarChart data={cls.weekly} margin={{ top: 4, right: 4, bottom: 0, left: -14 }}><CartesianGrid stroke={T.grid} vertical={false} /><XAxis dataKey="week" {...ax} tick={{ ...ax.tick, fontSize: 9 }} /><YAxis {...ax} /><Tooltip {...tip} /><Bar dataKey="n" radius={[3, 3, 0, 0]}>{cls.weekly.map((d) => <Cell key={d.week} fill={d.n === maxWeekly ? T.alert : T.accent} />)}</Bar></BarChart></ResponsiveContainer></div></Panel>
      <div className="rounded p-3" style={{ background: T.surfaceHi, border: `1px solid ${T.border}` }}><p className="text-[10px] leading-[1.6]" style={{ color: T.textDim }}><b style={{ color: T.text }}>About this view.</b> Incidents shown here were logged by specials teachers (P.E., Technology, Art, Music) during class time with this homeroom. They do not represent the full behavioral picture for this class — homeroom incidents and office referrals are not included in this dataset. Color chart usage and home contact rates reflect specials teacher practice, not homeroom practice.</p></div>
    </>}</motion.div></AnimatePresence></div></div>;
}
