import { motion } from 'framer-motion';
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ConsistencyTable } from '../components/ConsistencyTable';
import { Note } from '../components/Note';
import { Panel } from '../components/Panel';
import { ax, fade, T, tip } from '../theme';

export function CoverageView({ data }) {
  return <motion.div {...fade} className="space-y-3"><Panel title="Specials logging coverage" sub="Active weeks = weeks with at least one incident logged · 11 weeks total in window"><Note>Music logged in only 4 of 11 weeks (36%). Music also has the highest median submission lag (6.8h) and the lowest confirmed incident-time rate (21%). This is consistent with delayed or infrequent form use. Cannot determine from data alone whether this reflects fewer incidents or incomplete logging.</Note><Note>P.E. recorded 66 of its 97 incidents in March. Confirm with the teacher whether this reflects a change in documentation practice before drawing conclusions from the trend.</Note><ConsistencyTable consistency={data.consistency} /></Panel><div className="grid gap-3 xl:grid-cols-[1.3fr_1fr]"><Panel title="Monthly incident count by specials"><div className="h-56"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.monthly} margin={{ top: 4, right: 8, bottom: 0, left: -14 }}><CartesianGrid stroke={T.grid} vertical={false} /><XAxis dataKey="month" {...ax} /><YAxis {...ax} /><Tooltip {...tip} /><Legend wrapperStyle={{ fontSize: 10, color: T.textDim }} />{[['PE', T.accent], ['Technology', T.green], ['Art', T.amber], ['Music', T.alert]].map(([k, c]) => <Line key={k} type="monotone" dataKey={k} stroke={c} strokeWidth={2} dot={{ r: 3, fill: c }} />)}</LineChart></ResponsiveContainer></div></Panel><Panel title="Notes on interpretation"><div className="space-y-2.5 text-[11px] leading-[1.6]" style={{ color: T.textDim }}><p><b style={{ color: T.text }}>Art low volume.</b> 1.63 incidents per logging day. This may reflect a quieter classroom or less consistent form use — data alone cannot distinguish the two.</p><p><b style={{ color: T.text }}>Lag and timing accuracy.</b> Teachers who log same-day have near-complete timing data. Music's 6.8h lag is the likely cause of its 21% confirmed-time rate. Timing analysis for Music is unreliable.</p><p><b style={{ color: T.text }}>22 records without a specials label.</b> Most are from January before the field was consistently used. Labeled 'Unknown' in all views — not assigned to any teacher.</p></div></Panel></div></motion.div>;
}
