import { motion } from 'framer-motion';
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { HeatmapGrid } from '../components/HeatmapGrid';
import { Note } from '../components/Note';
import { Panel } from '../components/Panel';
import { ax, fade, T, tip } from '../theme';

export function TimingView({ data }) {
  const maxDow = Math.max(...data.dow.map((d) => d.rate));
  return <motion.div {...fade} className="space-y-3"><div className="grid gap-3 xl:grid-cols-2"><Panel title="Incidents per school day by weekday" sub="Normalized by school days logged in that weekday slot"><Note>Raw counts show Wednesday highest (65). After normalization: Monday leads at 8.67/day. Wednesday had more Wednesdays in the data window, not proportionally more incidents.</Note><div className="h-48"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.dow} margin={{ top: 4, right: 4, bottom: 0, left: -14 }}><CartesianGrid stroke={T.grid} vertical={false} /><XAxis dataKey="day" {...ax} /><YAxis {...ax} domain={[0, 10]} /><Tooltip {...tip} formatter={(v) => [`${v.toFixed(2)} / day`]} /><Bar dataKey="rate" radius={[3, 3, 0, 0]}>{data.dow.map((d) => <Cell key={d.day} fill={d.rate === maxDow ? T.alert : T.accent} />)}</Bar></BarChart></ResponsiveContainer></div></Panel><Panel title="Incident time distribution" sub="Confirmed incident times only (142 records) · uncertain before-9am block muted"><div className="h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.timeBlocks} margin={{ top: 4, right: 4, bottom: 28, left: -14 }}><CartesianGrid stroke={T.grid} vertical={false} /><XAxis dataKey="block" {...ax} angle={-25} textAnchor="end" interval={0} tick={{ ...ax.tick, fontSize: 9 }} /><YAxis {...ax} /><Tooltip {...tip} /><Bar dataKey="n" radius={[3, 3, 0, 0]}>{data.timeBlocks.map((d) => <Cell key={d.block} fill={d.uncertain ? T.muted : T.green} opacity={d.uncertain ? 0.38 : 1} />)}</Bar></BarChart></ResponsiveContainer></div></Panel></div><Panel title="Incident time by day and hour block" sub="Confirmed incident times only · 9am–3pm window · before-9am excluded"><HeatmapGrid heatmap={data.heatmap} /><p className="mt-2 text-[10px] leading-5" style={{ color: T.textDim }}>106 of 248 records have submission time only and are excluded. Before-9am incidents appear in the chart above but are omitted from the grid due to timing ambiguity.</p></Panel></motion.div>;
}
